### ISSUE TITLE
KeyError: 'Diluted Average Shares'

### ISSUE THREAD

**Issue by vipulgupta1011** [akashaero/Intrinsic-Value-Calculator#3]
Getting this error which running "python get_fair_value.py MSFT 12.05 28.3".

There seems to be no 'Diluted Average Shares' key in the 42 rows of income for MSFT

Error details : 
```
Traceback (most recent call last):
  File "/home/nlp/vkg5164/software/anaconda3/envs/stonks/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3790, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Diluted Average Shares'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nlp/vkg5164/code/Intrinsic-Value-Calculator/get_fair_value.py", line 70, in <module>
    current_price, total_shares, prev_rev_growth, starting_rev, prev_fcf_margin = get_info(ticker)
                                                                                  ^^^^^^^^^^^^^^^^
  File "/home/nlp/vkg5164/code/Intrinsic-Value-Calculator/provider.py", line 66, in get_info
    buybacks        = get_rates(income.loc['Diluted Average Shares'])
                                ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlp/vkg5164/software/anaconda3/envs/stonks/lib/python3.11/site-packages/pandas/core/indexing.py", line 1153, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlp/vkg5164/software/anaconda3/envs/stonks/lib/python3.11/site-packages/pandas/core/indexing.py", line 1393, in _getitem_axis
    return self._get_label(key, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlp/vkg5164/software/anaconda3/envs/stonks/lib/python3.11/site-packages/pandas/core/indexing.py", line 1343, in _get_label
    return self.obj.xs(label, axis=axis)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/nlp/vkg5164/software/anaconda3/envs/stonks/lib/python3.11/site-packages/pandas/core/generic.py", line 4236, in xs
    loc = index.get_loc(key)
          ^^^^^^^^^^^^^^^^^^
  File "/home/nlp/vkg5164/software/anaconda3/envs/stonks/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3797, in get_loc
    raise KeyError(key) from err
KeyError: 'Diluted Average Shares'
```

**Comment by akashaero** [comment]
Try these in your virtual environment and run that command again.

'python -m pip uninstall yfinance'
`python -m pip install git+https://github.com/ranaroussi/yfinance@feature/cookie-and-crumb`

**Comment by akashaero** [comment]
Marking this issue as closed
